### ISSUE TITLE
Support zig.

### ISSUE THREAD

**Issue by fire** [libriscv/godot-sandbox#100]
> Zig is definitely a cool language - it actually doesn't require a RISC-V toolchain
>
> you can just download Zig and directly get RISC-V executables from a one-liner

So a new docker container?

**Comment by fwsGonzo** [comment]
Yes, we just really like/prefer the reproducibility of having a container that works the same way on all systems.

**Comment by fire** [comment]
I have interest in this so am keeping the issue open.

**Comment by fwsGonzo** [comment]
PR: https://github.com/libriscv/godot-sandbox/pull/118
