### ISSUE TITLE
Prune Docker containers

### ISSUE THREAD

**Issue by fwsGonzo** [libriscv/godot-sandbox#113]
There are 8 pages of old (big) docker containers that have since been trimmed down.

We could perhaps use https://github.com/marketplace/actions/ghcr-pruning for this.

Any takers?

**Comment by fire** [comment]
Did we complete this task? saw mention in github

**Comment by fwsGonzo** [comment]
No, it's not done and unrelated to build times

**Comment by Ughuuu** [comment]
Why would this even be of interest? If there are unused versions, leave them. People use latest anyway. It won't matter much. I would not invest any time in this.
