### ISSUE TITLE
godot-cpp has renamed this double precision variable to GODOT_PRECISION

### ISSUE THREAD

**Issue by fire** [libriscv/godot-sandbox#125]
> The upstream godot-cpp has renamed this variable to GODOT_PRECISION: [godotengine/godot-cpp#1583](https://github.com/godotengine/godot-cpp/pull/1583)

From aaronfranke

**Comment by fwsGonzo** [comment]
Does this affect this project? Looks like only a CMake change.

**Comment by fire** [comment]
Unclear so I put it here to be tracked. Didn’t evaluate yet.

**Comment by fire** [comment]
I don't think we're affected.
