### ISSUE TITLE
Setup "api.hpp" for autocomplete

### ISSUE THREAD

**Issue by fire** [libriscv/godot-sandbox#140]
How do you enable auto-completion in VSCode for C++?

**Comment by fwsGonzo** [comment]
Add this folder: https://github.com/libriscv/godot-sandbox/tree/main/program/cpp/api

**Comment by fire** [comment]
Todo: add a section to the readme

**Comment by fwsGonzo** [comment]
Auto-completion in your own editor is much better with CMake, as you would symlink the cmake directory in godot-sandbox into your project and just build using a simple script. The symlink gives access to api.hpp and the editor auto-generates the c++ API on first save in the godot editor. Which you probably only care to do once. After that you have the whole thing, and you set your editor to perform an action on save, like `cmake --build` or something.

**Comment by fwsGonzo** [comment]
There is now a full run-time API generated based on the state of everything loaded into the engine, which gets written to the (current) project folder. When using Docker the remaining API is in the container, but also in the godot-sandbox repo. The recommendation is just to have the repo somewhere for your editor to see the includes.
