### ISSUE TITLE
 Investigate macos based riscv compile package

### ISSUE THREAD

**Issue by fire** [libriscv/godot-sandbox#147]
I don't want to launch docker.

**Comment by fwsGonzo** [comment]
Are you having trouble with getting Docker to work?

**Comment by fire** [comment]
When the docker build breaks it's very difficult.

**Comment by fwsGonzo** [comment]
Sounds like we could improve that part then?

**Comment by fwsGonzo** [comment]
I'm going to close this as a duplicate of https://github.com/libriscv/godot-sandbox/issues/141
