### ISSUE TITLE
Reroute printing/stdout to a callable

### ISSUE THREAD

**Issue by fwsGonzo** [libriscv/godot-sandbox#154]
LuaJit is not really making it easy to route prints to anything-but-stdout, but we can just reroute the entire Sandbox stdout to a Callable

**Comment by fire** [comment]
Callable or a callback that is virtual works too

**Comment by fwsGonzo** [comment]
Added a callback mechanism: https://github.com/libriscv/godot-sandbox/commit/a2e0b5ab9c6deeb9f42d7ce12722a50aa770d1c0
