### ISSUE TITLE
Errors on project reload and cannot create Sandbox scripts

### ISSUE THREAD

**Issue by Koanyaku** [libriscv/godot-sandbox#160]
Godot version is v4.3.stable.official [77dcf97d8].
godot-sandbox version is 0.20.

After installing the addon, multiple of these almost the same error messages pop up:

![bug1](https://github.com/user-attachments/assets/aa33d0c2-dfef-4e6d-80fd-33913302504c)

This happens every time the project is reloaded.

The ability to create a script in any other language than GDScript is also not possible:

![bug2](https://github.com/user-attachments/assets/a52e9aa3-0d10-4876-9562-77898fd1acc3)

Also, for some reason, the documentation for the "Sandbox" node is missing. The option is greyed out and ctrl-left clicking on the class in the script editor does nothing.

![bug3](https://github.com/user-attachments/assets/1ae46326-0a5a-4b40-becb-ef42bd966f9a)

**Comment by fwsGonzo** [comment]
The root cause is probably because Docker is not installed.

We have documentation here: https://libriscv.no/docs/godot/intro/

But I can see that Docker needs to be mentioned. It's also possible to use CMake if you have a RISC-V toolchain. What OS is this?

**Comment by Koanyaku** [comment]
My OS is Windows 10 build 19045.4894.

But, I need to install Docker in order to properly run this addon? I am not trying to build it or anything.

**Comment by fwsGonzo** [comment]
There are currently two ways to build programs: 1. Docker image 2: Locally using CMake. The sandbox uses the RISC-V architecture and so the compiler toolchain needed is a RISC-V one, typically RISC-V GNU toolchain. It's not always so easy to find good custom toolchains on Windows.

In there future there will be a web service that compiles through a REST API. But one step at a time.

**Comment by Koanyaku** [comment]
Oh, okay. But, I am still confused. I downloaded the addon zip from the releases page, and dropped the files into the addons in my Godot project, but I also need to go and install Docker, otherwise the addon won't work properly?

**Comment by fwsGonzo** [comment]
For a shipped game, nothing is needed outside of the addon. But in order to compile C++ to RISC-V you'll need a compiler from somewhere. That's just how systems languages work. Windows is an end-user OS, where developing stuff is hard. On Linux installing a RISC-V compiler is a one-liner. Same in WSL2. But I can't tell you how to install a RISC-V toolchain on vanilla Windows. I don't even have it!

Hence, we provide Docker as an alternative.

**Comment by Koanyaku** [comment]
Oh, I get it now, thanks. Sorry, I'm not really knowledgeable about this stuff. The whole time I thought you meant building the addon itself. Also, I guess I really _should've_ read the documentation, since it does say on the C++ page that you need Docker. Sorry for wasting your time.

**Comment by fwsGonzo** [comment]
I definitely think we should make that more clear. The fact that we're having this conversation means we need to update the docs a bit. No problem.

**Comment by Koanyaku** [comment]
Yes, I think you should probably put it in the README somewhere, since it's such an important part of the addon. Thanks for the help anyways!
