### ISSUE TITLE
Guarantees does not provide information on these limits or how to configure them

### ISSUE THREAD

**Issue by fire** [libriscv/godot-sandbox#162]
Godot Sandbox -> Sandbox: Your guarantees section lists what it does but does not provide information on these limits or how to configure them. If you want this to be a platform, you need to provide configurability with the defaults mentioned.

**Comment by fire** [comment]
> There are some restriction functions in the Sandbox right now, but it's very restrictive. If you enable it, you have to specify every single Variant, Object etc. that you want to use up-front. That API is there in case you do want a Sandbox that is giga-restrictive.

Can we do a trace and permit workflow like selinux?

**Comment by fwsGonzo** [comment]
I was thinking that you could just install a Callable that gets called on each thing the Sandbox complains about. Not sure how informative the callback will be, but we will try to provide enough information.

**Comment by fire** [comment]
The idea is a flag on the sandbox gives us a trace. We can review the trace and use it as a whitelist. 

See selinux.

**Comment by fwsGonzo** [comment]
That makes sense if you can know all the things up-front, but there may be dynamic things too. A trace would indeed give you the option to avoid the callable, by up-front allowing something. It's just not going to be everything.

**Comment by fire** [comment]
I don't understand the feature you're proposing.

**Comment by fwsGonzo** [comment]
I've now implemented just-in-time callbacks for allowing objects, classes and resources. It should give the most control over restrictions. It's still possible to add specific objects beforehand, which makes it possible to iterate over a tree and just add each node etc.
