### ISSUE TITLE
Add preprocessor macro documentation

### ISSUE THREAD

**Issue by fire** [libriscv/godot-sandbox#165]
I think we recently added c/c++ preprocessor macros to generate accessors (something like GD_ACCESSOR_SUGAR(type, name, type1, arg1, type2, arg2, type3, arg3...) along with a voidcall variant.

But I forget where we mentioned it.

**Comment by fwsGonzo** [comment]
Yes, that's indeed the case. They're just called `METHOD(name)` now. [Examples here](https://libriscv.no/docs/godot/sugar#using-methods-on-other-types).
