### ISSUE TITLE
Compare dedicated sandbox node vs attached to an existing node as a script

### ISSUE THREAD

**Issue by fire** [libriscv/godot-sandbox#166]
Explain that you can run the scripts in a dedicated sandbox node or attached to an existing node like any other script and preface the recommendation of using a sandbox mode.

A single "Comparison" section would help us quickly understand why you want one style over the other.

**Comment by fwsGonzo** [comment]
Makes sense

**Comment by fwsGonzo** [comment]
I added information about dedicated sandboxes: http://localhost:3000/docs/godot/sandbox#dedicated-sandbox-nodes
