### ISSUE TITLE
Restarting to load properties is annoying

### ISSUE THREAD

**Issue by fire** [libriscv/godot-sandbox#171]
Restarting to load properties is annoying.

**Comment by fwsGonzo** [comment]
I don't know how to proceed with this. If someone can point out the exact solution or provide a PR with the improvement, that would be nice.

**Comment by fwsGonzo** [comment]
After a discussion with @Ughuuu we realized that it may be possible to use the list of instantiated ELF scripts to reload them without having to iterate the whole project to find ELF script instances.

Maybe that's a way forward.

**Comment by fwsGonzo** [comment]
Figured it out after a bunch of back and forth.

Implemented with https://github.com/libriscv/godot-sandbox/commit/dfb522e70de8b9b2aa21a05741c83040325d1898
