### ISSUE TITLE
Instruction is confusing for module building

### ISSUE THREAD

**Issue by fire** [libriscv/godot-sandbox#205]
```
If you want to build this as a module, simply download the sandbox.zip from releases, unzip it, and copy it to the modules folder in godot, build it:

scons module_sandbox_enabled=True disable_exceptions=False target=editor
```

On macos.

Wanting double builds.

**Comment by fire** [comment]
Must download `static-sandbox-gdextension`

Like https://github.com/libriscv/godot-sandbox/actions/runs/11646043564/artifacts/2136905715

**Comment by fire** [comment]
`#modules/sandbox/bin` Does not exist.

**Comment by fire** [comment]
1. Rename  static-sandbox  to sandbox
2. Put it as godot/modules/sandbox

**Comment by fire** [comment]
Horray.

![image](https://github.com/user-attachments/assets/8775f5fb-7ad8-49d6-aca5-e444b59a335e)

**Comment by fwsGonzo** [comment]
Are the instructions still confusing?

**Comment by fire** [comment]
1. Rename static-sandbox to sandbox
3. Put it as godot/modules/sandbox
4. bin and ext folders are required but are git ignored.

**Comment by fire** [comment]
Same as https://github.com/libriscv/godot-sandbox/issues/206
