### ISSUE TITLE
Monitoring properties gets saved with the project

### ISSUE THREAD

**Issue by fwsGonzo** [libriscv/godot-sandbox#218]
We need to investigate how to disable monitoring properties from ending up saved in project files and polluting git history

**Comment by fire** [comment]
Setting the properties editor-only usage will tell godot to hide them.

**Comment by fwsGonzo** [comment]
I don't want to hide them, just prevent the values from being stored in project.godot

**Comment by fwsGonzo** [comment]
There was a default argument to PropertyInfo that I wasn't using. Fixed now.
