### ISSUE TITLE
Add way of fetching dictionaries that doesn't explode if missing.

### ISSUE THREAD

**Issue by fire** [libriscv/godot-sandbox#219]
`args["verbose"].value();`

**Comment by fire** [comment]
Maybe arrays too.

**Comment by fire** [comment]
Godot has a variation of get does this pattern, get the value or return the default.

**Comment by fwsGonzo** [comment]
This already existed in Dictionary, although I have added `value_or(default)` for the proxy. Array never had one for godot-cpp, but I've added at_or() and get_or() for the proxy. 3b4cb5b
