### ISSUE TITLE
Replace malloc

### ISSUE THREAD

**Issue by fire** [libriscv/godot-sandbox#220]
https://github.com/godotengine/godot/pull/99427

**Comment by fwsGonzo** [comment]
The custom allocator used by godot-sandbox is different in that it manages a guest address space. It's basically a remote heap.

mimalloc will definitely improve the overall performance of Godot though, and it's going to improve Godot Sandbox itself as a consequence. At least on Linux.

**Comment by fire** [comment]
Makes sense, closing.
