### ISSUE TITLE
Given a random elf riscv64 linux binary we don't know the call signature.

### ISSUE THREAD

**Issue by fire** [libriscv/godot-sandbox#223]
It would be useful for documentation to embed the call signature into the elf browser in Godot Engine.

**Comment by fire** [comment]
> Future things, but we're not feeling them right now.

**Comment by fire** [comment]
`Symbol_name, argument string, argument string, argument string ...`

Looks exactly like how the Godot Engine binds things

```c++
ClassDB::bind_method(D_METHOD("set_live_preview", "p_enable"),
            &RenIK::set_live_preview); (edited)
D_METHOD("set_live_preview", "p_enable")
```

**Comment by fwsGonzo** [comment]
Implemented in https://github.com/libriscv/godot-sandbox/pull/225

**Comment by fwsGonzo** [comment]
I will close this as the new method of designing public API covers a lot of ground already. We can improve it later by trying to use the dynamic method that godot-cpp uses, however that requires access to instantiating public API methods during main().
