### ISSUE TITLE
Integrate Zig toolchain into Godot Sandbox

### ISSUE THREAD

**Issue by fwsGonzo** [libriscv/godot-sandbox#233]
Without a CMake project, people won't be able to build complex projects with dependencies and settings. We now support Zig toolchains, which only requires Zig to be available in PATH.

- [x] Add Zig toolchain support
- [x] Add CMake project that uses Zig toolchain to Github Actions
- [x] Add access to C++ API
- [x] Add access to the Godot run-time C++ API (fetch to build folder)
- [x] Fetch the C++ API into build folder
- [x] Add Zig toolchain to unittests
- [x] Run demo project with Zig toolchain
- [x] Test demo project with LTO and binary translation
- [x] Add MINIMAL option to build even smaller programs

When everything is in place the build system will be dependency free. No submodules, no copying APIs around etc.

**Comment by fire** [comment]
⭐ ⭐ ⭐

**Comment by fwsGonzo** [comment]
Now released!
