### ISSUE TITLE
Host zig inside of a godot elf?

### ISSUE THREAD

**Issue by fire** [libriscv/godot-sandbox#235]
Is it possible?

**Comment by fwsGonzo** [comment]
No, it doesn't make any sense. For the same reason you download Godot, you can also download Zig. Zig isn't used after you have compiled the program, so it's not something that we should ship with a game.

... but we can make Zig downloadable similar to how you can download web export in the editor.

**Comment by fwsGonzo** [comment]
The Zig toolchain now verifiably builds on all 3 desktop platforms: https://github.com/libriscv/godot-sandbox-programs
The CI configurations show the dependencies and steps of each platform
