### ISSUE TITLE
Disable Docker versioning checks

### ISSUE THREAD

**Issue by fire** [libriscv/godot-sandbox#237]
My friend was confused as to why dragging an elf to a node script loads docker. The docker program is not installed.

> A godot sandbox, with a program loaded by the user, where the program is ONLY allowed to access the domain https://gist.github.com/ - and a program loaded by this sandbox that gets a gist like https://gist.github.com/fire/3d096ddb38b696d4886b618cce5452f5 with an HTTP GET request and loads it into a textbox

**Comment by fire** [comment]
As far as I know, there are two modes.

1. We load the elf file from a buffer in the scene tree property
2. We extend an existing node as a script.

**Comment by fwsGonzo** [comment]
I think that's the version checking code trying to use Docker.

**Comment by fire** [comment]
Can `Enable Docker` be disabled by default to avoid developer surprise?

**Comment by fwsGonzo** [comment]
The whole extension stops working by default if we do that. Right now when you install Godot Sandbox and press Ctrl+S in any language window, it will just work.

**Comment by fire** [comment]
What's the fallout from removing the version checks altogether?

**Comment by fwsGonzo** [comment]
If the API changes in a way that makes a program stop working, there's no versioning to indicate that you need to rebuild the program. That versioning also exists for CMake builds but I don't know if it works or not.

**Comment by fire** [comment]
Is there no feedback on load failure async when we try to load?

**Comment by fwsGonzo** [comment]
If the sandbox fails to load, then yes you will be able to see that.

**Comment by fire** [comment]
I mean to try to rebuild the program on async load failure instead of checking at the start.

**Comment by fwsGonzo** [comment]
That doesn't make any sense. A program can randomly fail:
```
int main() {
    if (rand() % 2) assert(0);
}
```

**Comment by fwsGonzo** [comment]
When C++ is detected, disable version check: https://github.com/libriscv/godot-sandbox/pull/238

This avoids breaking other languages, which is nice.
