### ISSUE TITLE
Zig musl-libc++ programs fail to boot on Windows

### ISSUE THREAD

**Issue by fwsGonzo** [libriscv/godot-sandbox#245]
Looks like system call emulation bug. Could also be native syscalls behaving badly on Windows, but less likely.

MRP:
[gist_getter.zip](https://github.com/user-attachments/files/18278842/gist_getter.zip)

**Comment by fire** [comment]
Use a windows 10 vm. They're free and you're legally allowed to use them for testing. copy-protection-side they stop working in a month and so 
https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/

**Comment by fwsGonzo** [comment]
Fixed with https://github.com/libriscv/libriscv/pull/282
