### ISSUE TITLE
A CMake build system for the C++ script?

### ISSUE THREAD

**Issue by fwsGonzo** [libriscv/godot-sandbox#36]
I'm not exactly sure how to support that with C++ scripting, but it would be nice since it trivializes adding external libraries.

**Comment by fire** [comment]
Discussed with @fwsGonzo 

Can add existing libraries to godot-sandbox projects.

Open question how to support with a docker build container.

We can only currently add single-header-only libraries.

**Comment by fwsGonzo** [comment]
Implemented here: https://github.com/libriscv/godot-sandbox/pull/148
