### ISSUE TITLE
Move libriscv_settings.h to another folder

### ISSUE THREAD

**Issue by fwsGonzo** [libriscv/godot-sandbox#49]
Perhaps it could be moved to src

**Comment by fire** [comment]
Do you still want a pr for this?

**Comment by fwsGonzo** [comment]
Yes, I think de-cluttering the root folder is nice!

**Comment by fwsGonzo** [comment]
Fixed here: https://github.com/libriscv/godot-sandbox/pull/107/commits/f5b0133739dd77669cacb2bcfaab129d1ed3fdeb
