### ISSUE TITLE
Automatic Docker pull?

### ISSUE THREAD

**Issue by fwsGonzo** [libriscv/godot-sandbox#66]
Right now, on each release, the API of the C++ and Rust languages are usually also updated, which requires the latest version of the respective docker container. In the case of C++, it's `godot-cpp-compiler` and for Rust `godot-rust-compiler`. These are created from the upstream `ghcr.io/libriscv/cpp_compiler` and `ghcr.io/libriscv/rust_compiler`.

Hence, in order to be on the latest version, one must:
```
docker stop godot-cpp-compiler
docker rm godot-cpp-compiler
docker pull ghcr.io/libriscv/cpp_compiler
```

Should this be done automatically? I don't like forcing the latest version, as people may be sitting on specific version of the extension.

**Comment by fire** [comment]
Is this documented anywhere?

**Comment by Ughuuu** [comment]
I still think a window for managing versions and docker running status would make sense

**Comment by Ughuuu** [comment]
Also, maybe a project setting (eg cpp-api version and rust-api version) by default set to latest. People if they want can set to whatever they want in there, and then our docker pull would just get that version.
I think the default being latest wouldn't be too bad, or we could version api with sandbox(eg version 0.9 of sandbox and version 0.9 of api. Then we release api only 0.9.1, 0.9.2, ...

**Comment by fire** [comment]
Fixed by https://github.com/libriscv/godot-sandbox/pull/77

**Comment by fire** [comment]
Released https://github.com/libriscv/godot-sandbox/releases/tag/v0.12
