### ISSUE TITLE
Cannot represent time as 64bit float.

### ISSUE THREAD

**Issue by fire** [libriscv/godot-sandbox#69]
> gdscript floats are float64 Float is now 32-bit (matching default real_t) https://github.com/libriscv/godot-sandbox/commit/0c3b5552da84b13f5d56c65f275e3d1ef3b36c9a

If you force doubles to 32 bit you break animation system timing and a bunch of other systems like our 64 bit real_t builds.

So if forced to make a decision. I would prefer float64_t over float32_t if we have to pick one, or support both float32_t and float64_t

**Comment by fire** [comment]
This is a problem because gdscript expects floats to be 64bit and godot-sandbox currently expects floats to be 32 bit.

**Comment by fwsGonzo** [comment]
Thanks for reporting. Fixed with https://github.com/libriscv/godot-sandbox/commit/908f76425a409e2f1eea0877e5dae6cbff785ae4.
