### ISSUE TITLE
`as_node2d` syntax is awkward

### ISSUE THREAD

**Issue by fire** [libriscv/godot-sandbox#71]
Instead of as_node2d godot uses:

```c++
Node2D *node_2d = cast_to<Node2D>(node);
```

**Comment by fwsGonzo** [comment]
I've pushed a new container with `cast_to<Object, Node, Node2D, Node3D>`

**Comment by fwsGonzo** [comment]
API implementation here: https://github.com/libriscv/godot-sandbox/pull/70/commits/a00721598bc1c98210ca0895b766ffe452d119ae
