### ISSUE TITLE
Metadata in elf binaries

### ISSUE THREAD

**Issue by fire** [libriscv/godot-sandbox#73]
The godot-sandbox elf binaries lack a way to describe metadata.

Like build times, compatibility, version, authorship origins, how to interrogate for debugging purposes?

Like is a godot-sandbox elf.

```
[
  {
    "args": [],
    "name": "_GLOBAL__sub_I_properties"
  },
  {
    "args": [],
    "name": "_physics_process"
  }
]
```

**Comment by fwsGonzo** [comment]
We don't really have a versioning system yet, but we could embed a version into the API

**Comment by Ughuuu** [comment]
About this, I could see that we have a method inside the client, eg _get_metadata, which returns something:
Metadata {
  version
  ..
}

**Comment by fwsGonzo** [comment]
I've added a version and language information to ELF programs now, and a way to retrieve it using the emulator.

```C++
#define STR2(x) #x
#define STR(x) STR2(x)
__asm__(".pushsection .comment\n\t"
		".string \"Godot C++ API v" STR(VERSION) "\"\n\t"
		".popsection");
```
This will add `Godot C++ API v2` to the .comment section of the binary.

**Comment by fwsGonzo** [comment]
Forgot to mention that the language is also exposed, so we can identify the programming language of an ELF now.
