### ISSUE TITLE
Web interrogator that we can drag `.elf` to ask them for their metadata.

### ISSUE THREAD

**Issue by fire** [libriscv/godot-sandbox#74]
See example from https://github.com/libriscv/godot-sandbox-demo

[player.zip](https://github.com/user-attachments/files/16820501/player.zip)

```
[
  {
    "args": [],
    "name": "_GLOBAL__sub_I_properties"
  },
  {
    "args": [],
    "name": "_physics_process"
  }
]
```

**Comment by fire** [comment]
Think like godbolt.

https://godbolt.org/

1. stage 1 describe the debug information
2. stage 2 compiled c++ or rust
3. stage 3 public web api from Godot Engine editor.

**Comment by fwsGonzo** [comment]
I do have a machine we can use, which I can install a VM on that can build from remote requests. I think that will cover most peoples needs. I have a very high ping to the US though.

**Comment by fire** [comment]
We discussed using digital ocean.

**Comment by Ughuuu** [comment]
We don't really need to use any of locally hosted or digital ocean. We can use github actions with open source repo (I think has limits of 20-30 parallel builds maybe). We start the job and get the result.

**Comment by fire** [comment]
How will I be able to drag random binaries then?

**Comment by Ughuuu** [comment]
Maybe I didn't understand then well what this is trying to achieve. But it woudl be cool if player could just put c++ code (or rust) and it would compile it with github action, and then run it.

**Comment by fire** [comment]
Well the idea is being able to inspect elf binaries to see if they’re usable without source

**Comment by fire** [comment]
Closing for now until we have more bandwidth.
