### ISSUE TITLE
Godot Engine "double" builds?

### ISSUE THREAD

**Issue by fire** [libriscv/godot-sandbox#75]
@Ughuuu Did you get "double" builds working with godot sandbox? It can be two releases zips -- one for the single, and the other for double.

**Comment by Ughuuu** [comment]
Hm, not sure i tried to get them. They should be in same zip tho i think. Otherwise distribution will be harder.

**Comment by fwsGonzo** [comment]
PR here: https://github.com/libriscv/godot-sandbox/pull/101
