### ISSUE TITLE
Resolving .elf Script Naming Conflicts for CDN Deployment

### ISSUE THREAD

**Issue by fire** [libriscv/godot-sandbox#90]
Naming `.elf` scripts based on source paths leads to conflicts when serialized into scenes and stored on a CDN. Changes in path due to CDN storage alter the script's global name, breaking code references.

#### Discussion Points:

- **Current Naming Convention**: Ties `.elf` script names to their source file paths, causing issues when paths change.
- **Proposed Solution**: Append a UUID to folder names to prevent conflicts (e.g., `res://some-uuid-long-form/player.elf`).
- **Alternative Suggestions**:
  - Use human-readable random words like "angry-horse" for better intuitiveness.
  - Limit name length to three words to avoid verbosity.

#### Tools and Libraries:

- **guid-in-words**: Converts GUIDs to words; concerns about name length exist.

#### Concerns:
- Need a renaming mechanism that doesn't affect compilation.
- Require a method to generate unique, concise names for usability and conflict prevention.

**Comment by fire** [comment]
`@export var player_elf : Sandbox` works but lacks autocomplete.

**Comment by fwsGonzo** [comment]
I think we can close this now that we can just load arbitrary programs directly into the Sandboxes without needing any ELF scripts at all
