### ISSUE TITLE
Node(".") syntax isn't a common syntax in Godot Engine

### ISSUE THREAD

**Issue by fire** [libriscv/godot-sandbox#95]
@lyuma mentioned surprise with the `Node(".")` "." being a nodepath.

**Comment by fwsGonzo** [comment]
I like that syntax, but an alternative syntax can be proposed and used in addition to the current one.

**Comment by fire** [comment]
I think we should either keep it or remove it. I'm trending towards removing it, but since you liked the design -- what will probably happen is we'll do nothing.

**Comment by fwsGonzo** [comment]
What is the alternative then?

**Comment by lyuma** [comment]
In standard Godot scripting, you would call either get_node(NodePath) or get_node_or_null(NodePath).

That said, GDScript also has a shorthand $(^"SomeNodepath") and I could see Node("SomeNodepath") being akin to that.

What actually confused me is that Object("SomeString") is different from
Node("SomeString") and Node3D("SomeString"). Or even if Engine("Engine") is different than Object("Engine").

**Comment by fwsGonzo** [comment]
We can change the Object constructor and instead make simple wrappers around the globals:
```c++
struct Engine {
    Object get_singleton() { ... here ... }
};
```

**Comment by fwsGonzo** [comment]
I've added `get_node(...)` and `get_node()`, as well as a wrapper for Engine.
